# Generated by Django 4.2.5 on 2023-09-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='cat_imgs/')),
            ],
        ),
        migrations.AlterField(
            model_name='color',
            name='color_codigo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='color',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='size',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
