# Generated by Django 4.2.5 on 2023-09-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='image',
            field=models.ImageField(upload_to='marca_imgs/'),
        ),
    ]
